apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-kafka-stream-service
  name: java-kafka-stream-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: java-kafka-stream-service
  ports:
    - protocol: "TCP"
      name: java-kafka-stream-service-svc
      port: 20931
      targetPort: 20931
      nodePort: {{ .Values.stream.service.nodePort | default 30932 }}
---
