apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-kafka-stream-service-log-pv
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/java-kafka-stream-service/logs
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-kafka-stream-service-log-pvc
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: java-kafka-stream-service-log-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
  storageClassName: local-path
---
