apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-jooq-rest-api
  name: java-jooq-rest-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.jooq.rest.api.replicas | default 1 }}
  selector:
    matchLabels:
      app: java-jooq-rest-api
  template:
    metadata:
      labels:
        app: java-jooq-rest-api
    spec:
      containers:
        - name: java-jooq-rest-api
          image: "{{ .Values.image.registry }}/rokroot/java-jooq-rest-api:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: rest
              hostPort: 20930
              containerPort: 20930
          resources:
            requests:
              cpu: {{ .Values.jooq.rest.api.cpu | default 1 }}
              memory: {{ .Values.jooq.rest.api.memory | default "8Gi" }}
            limits:
              cpu: {{ mulf ( .Values.jooq.rest.api.cpu | int ) 2 | int }}
              memory: {{ ( mulf ( ( .Values.jooq.rest.api.memory | toString | regexFind "[0-9.]+" ) | int) 2 | int ) }}Gi
          volumeMounts:
            - name: java-jooq-rest-api-config
              mountPath: /opt/java-demo/jooq-rest-api/config
              readOnly: true
            - name: java-jooq-rest-api-log
              mountPath: /opt/java-demo/jooq-rest-api/logs
              readOnly: false
            - name: java-jooq-rest-api-file
              mountPath: /opt/java-demo/jooq-rest-api/files
              readOnly: false
          env:
            - name: TZ
              value: Asia/Seoul
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
            - "java"
            - "-jar"
            - "/opt/java-demo/jooq-rest-api/jooq-rest-api.jar"
            {{- if .Values.jooq.rest.api.java.opts }}
            {{- $opts := .Values.jooq.rest.api.java.opts | split " " }}
            {{- range $opt := $opts }}
            - {{ $opt | quote }}
            {{- end }}
            {{- end }}
      volumes:
        - name: java-jooq-rest-api-config
          configMap:
            name: java-jooq-rest-api-config
            items:
              - key: application.properties
                path: application.properties
              - key: log4j2.properties
                path: log4j2.properties
        - name: java-jooq-rest-api-log
          persistentVolumeClaim:
            claimName: java-jooq-rest-api-log-pvc
        - name: java-jooq-rest-api-file
          persistentVolumeClaim:
            claimName: java-jooq-rest-api-file-pvc
---
