apiVersion: v1
kind: Service
metadata:
  labels:
    app: jooq-rest-api
  name: jooq-rest-api
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: jooq-rest-api
  ports:
    - protocol: "TCP"
      name: jooq-rest-api-svc
      port: 20930
      targetPort: 20930
      nodePort: {{ .Values.jooq.rest.api.nodePort | default 30931 }}
---
