apiVersion: v1
kind: PersistentVolume
metadata:
  name: jooq-rest-api-log-pv
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/jooq-rest-api/logs
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jooq-rest-api-log-pvc
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: jooq-rest-api-log-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jooq-rest-api-file-pv
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/jooq-rest-api/files
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jooq-rest-api-file-pvc
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: jooq-rest-api-file-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path
---
