image:
  registry: docker.io
  tag: 0.0.1
  imagePullPolicy: IfNotPresent

stream:
  service:
    cpu: 2
    memory: 4Gi
    java:
      opts: "-Xms4g -Xmx8g -Dfile.encoding=UTF-8"
    replicas: 1
    nodePort: 30932

    application.properties: |
      stream.kafka.host=kafka-kafka-bootstrap.kafka
      stream.kafka.port=9092

    log4j2.properties: |
      rootLogger.level=INFO
      
      logger.netty.name=io.reactor.netty
      logger.netty.level=WARN

      logger.apache.name=org.apache
      logger.apache.level=INFO
      
      logger.kafka.name=org.apache.kafka
      logger.kafka.level=WARN
      
      logger.java-demo-core.name=kr.co.rokroot.java.demo.core
      logger.java-demo-core.level=DEBUG
      
      logger.java-demo-kafka-stream-service.name=kr.co.rokroot.java.demo.kafka.stream.service
      logger.java-demo-kafka-stream-service.level=DEBUG
---
