apiVersion: v1
kind: ConfigMap
metadata:
  name: stream-service-config
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    logging.config=config/log4j2.properties

    {{ index .Values.stream.service "application.properties" | nindent 4 }}
  log4j2.properties: |
    name=PropertiesConfig
    property.filename=log4j2.properties

    appender.console.type=Console
    appender.console.name=STDOUT
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=%highlight{%-5level} [%thread] %cyan{%logger{1.3*}}[%method:%line] - %msg%n

    appender.rolling.type=RollingFile
    appender.rolling.name=RollingFile
    appender.rolling.fileName=logs/stream-service.log
    appender.rolling.filePattern=logs/stream-service.log.%d{yyyy-MM-dd}.%i.log
    appender.rolling.layout.type=PatternLayout
    appender.rolling.layout.pattern=[%d{HH:mm:ss.SSS}] [%-5level] [%thread] %logger{1.3*}[%method:%line] - %msg%n

    appender.rolling.policies.type=Policies
    appender.rolling.policies.time.type=SizeBasedTriggeringPolicy
    appender.rolling.strategy.type=DefaultRolloverStrategy
    appender.rolling.strategy.max=30

    rootLogger.appenderRefs=RollingFile, STDOUT
    rootLogger.appenderRef.rolling.ref=RollingFile
    rootLogger.appenderRef.stdout.ref=STDOUT

    {{ index .Values.stream.service "log4j2.properties" | nindent 4 }}
---
