apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stream-service
  name: stream-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.stream.service.replicas | default 1 }}
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
        - name: stream-service
          image: "{{ .Values.image.registry }}/rokroot/stream-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: stream
              hostPort: 20931
              containerPort: 20931
          resources:
            requests:
              cpu: {{ .Values.stream.service.cpu | default 2 }}
              memory: {{ .Values.stream.service.memory | default "16Gi" }}
            limits:
              cpu: {{ mulf ( .Values.stream.service.cpu | int ) 2 | int }}
              memory: {{ ( mulf ( ( .Values.stream.service.memory | toString | regexFind "[0-9.]+" ) | int) 2 | int ) }}Gi
          volumeMounts:
            - name: stream-service-config
              mountPath: /opt/rokroot-demo/stream-service/config
              readOnly: true
            - name: stream-service-log
              mountPath: /opt/rokroot-demo/stream-service/logs
              readOnly: false
          env:
            - name: TZ
              value: Asia/Seoul
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
            - "java"
            - "-jar"
            - "/opt/rokroot-demo/stream-service/rokroot-stream-service.jar"
            {{- if .Values.stream.service.java.opts }}
            {{- $opts := .Values.stream.service.java.opts | split " " }}
            {{- range $opt := $opts }}
            - {{ $opt | quote }}
            {{- end }}
            {{- end }}
      volumes:
        - name: stream-service-config
          configMap:
            name: stream-service-config
            items:
              - key: application.properties
                path: application.properties
              - key: log4j2.properties
                path: log4j2.properties
        - name: stream-service-log
          persistentVolumeClaim:
            claimName: stream-service-log-pvc
---
